version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sgca
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-sgca}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER:-sgca_user}
      MYSQL_PASSWORD: ${SGCA_DB_PASSWORD}
    ports:
      - '3316:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sgca-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${MYSQL_USER:-sgca_user}", "-p${SGCA_DB_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sgca:
    build: .
    container_name: spring_sgca
    ports:
      - '8090:8080'
    environment:
      SGCA_DB_PASSWORD: ${SGCA_DB_PASSWORD}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE:-sgca}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-sgca_user}
      SPRING_DATASOURCE_PASSWORD: ${SGCA_DB_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      SGCA_EMAIL_PASSWORD: ${SGCA_EMAIL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
    volumes:
      - uploads_data:/app/uploads
    networks:
      - sgca-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  uploads_data:

networks:
  sgca-network:
    driver: bridge
