version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_sgca
    restart: always
    environment:
      MYSQL_DATABASE: sgca
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3316:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sgca-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-padmin" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sgca:
    build: .
    container_name: spring_sgca
    ports:
      - '8090:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/sgca
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - sgca-network
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  sgca-network:
    driver: bridge
